-- Step 3: Add remaining enum values

ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'PRIMARY_UPPER';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'MIDDLE';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'SECONDARY';
ALTER TYPE "AgeGroup" ADD VALUE IF NOT EXISTS 'ADULTS';